"""Extract serialized Unity Mesh .asset files into deterministic Unreal-space OBJ files.

Unity stores meshes generated by editor tooling directly in YAML assets.  They
do not pass through the normal FBX/OBJ migration path, but the vertex and index
buffers are complete and lossless.  This tool decodes the channels needed by
the Starter Island water and underbody meshes and writes centimetre-scaled,
Unreal-axis OBJ files without modifying the Unity project.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import struct
from dataclasses import dataclass
from pathlib import Path


SOURCE_ASSETS = (
    "Assets/_Project/Art/Environment/StarterIsland/Terrain/Data/MD_Water_Pond_Main.asset",
    "Assets/_Project/Art/Environment/StarterIsland/Terrain/Data/MESH_StarterIsland_Underbody_Exact.asset",
    "Assets/_Project/Art/Environment/StarterIsland/VerticalRockKit_Sculpted/Meshes/MESH_VRKS_Transition_A.asset",
    "Assets/_Project/Art/Environment/StarterIsland/VerticalRockKit_Sculpted/Meshes/MESH_VRKS_Ledge_A.asset",
    "Assets/_Project/Art/Environment/StarterIsland/VerticalRockKit_Sculpted/Meshes/MESH_VRKS_Corner_A.asset",
    "Assets/_Project/Art/Environment/StarterIsland/VerticalRockKit_Sculpted/Meshes/MESH_VRKS_Straight_B.asset",
    "Assets/_Project/Art/Environment/StarterIsland/VerticalRockKit_Sculpted/Meshes/MESH_VRKS_End_A.asset",
    "Assets/_Project/Art/Environment/StarterIsland/VerticalRockKit_Sculpted/Meshes/MESH_VRKS_Corner_B.asset",
    "Assets/_Project/Art/Environment/StarterIsland/VerticalRockKit_Sculpted/Meshes/MESH_VRKS_Straight_A.asset",
    "Assets/_Project/Art/Environment/StarterIsland/VerticalRockKit_Sculpted/Meshes/MESH_VRKS_End_B.asset",
    "Assets/_Project/Art/Cinematics/Meshes/MSH_CIN_WarpTunnel.asset",
    "Assets/_Project/Art/Cinematics/Meshes/MSH_CIN_Asteroid_00.asset",
    "Assets/_Project/Art/Cinematics/Meshes/MSH_CIN_Asteroid_01.asset",
    "Assets/_Project/Art/Cinematics/Meshes/MSH_CIN_Asteroid_02.asset",
    "Assets/_Project/Art/Cinematics/Meshes/MSH_CIN_Asteroid_03.asset",
    "Assets/_Project/Art/Cinematics/Meshes/MSH_CIN_Asteroid_04.asset",
    "Assets/_Project/Art/Cinematics/Meshes/MSH_CIN_Asteroid_05.asset",
    "Assets/_Project/Art/Cinematics/Meshes/MSH_CIN_Asteroid_06.asset",
    "Assets/_Project/Art/Cinematics/Meshes/MSH_CIN_Asteroid_07.asset",
    "Assets/_Project/Art/Cinematics/Meshes/MSH_CIN_Asteroid_08.asset",
)


@dataclass(frozen=True)
class Channel:
    stream: int
    offset: int
    format: int
    dimension: int


def _capture(pattern: str, text: str, source: Path) -> str:
    match = re.search(pattern, text, re.MULTILINE)
    if not match:
        raise RuntimeError(f"Missing {pattern!r} in {source}")
    return match.group(1)


def _channels(text: str, source: Path) -> list[Channel]:
    start = text.index("    m_Channels:")
    end = text.index("    m_DataSize:", start)
    block = text[start:end]
    values = re.findall(
        r"    - stream: (\d+)\n"
        r"      offset: (\d+)\n"
        r"      format: (\d+)\n"
        r"      dimension: (\d+)",
        block,
    )
    if not values:
        raise RuntimeError(f"No vertex channels in {source}")
    return [Channel(*(int(value) for value in row)) for row in values]


def _submeshes(text: str, source: Path) -> list[dict[str, int]]:
    start = text.index("  m_SubMeshes:")
    end = text.index("  m_Shapes:", start)
    block = text[start:end]
    matches = re.finditer(
        r"  - serializedVersion: \d+\n"
        r"    firstByte: (\d+)\n"
        r"    indexCount: (\d+)\n"
        r"    topology: (\d+)\n"
        r"    baseVertex: (-?\d+)\n"
        r"    firstVertex: (\d+)\n"
        r"    vertexCount: (\d+)",
        block,
    )
    result = [
        {
            "firstByte": int(match.group(1)),
            "indexCount": int(match.group(2)),
            "topology": int(match.group(3)),
            "baseVertex": int(match.group(4)),
            "firstVertex": int(match.group(5)),
            "vertexCount": int(match.group(6)),
        }
        for match in matches
    ]
    if not result:
        raise RuntimeError(f"No submeshes in {source}")
    return result


def _floats(buffer: bytes, offset: int, dimension: int, value_format: int) -> tuple[float, ...]:
    if value_format == 0:
        return struct.unpack_from("<" + "f" * dimension, buffer, offset)
    if value_format == 1:
        return struct.unpack_from("<" + "e" * dimension, buffer, offset)
    raise RuntimeError(f"Unsupported floating vertex format {value_format}")


def _guid(source: Path) -> str:
    meta = source.with_suffix(source.suffix + ".meta")
    return _capture(r"^guid:\s*([0-9a-fA-F]+)$", meta.read_text("utf-8"), meta)


def _extract(source: Path, destination: Path) -> dict:
    text = source.read_text("utf-8")
    name = _capture(r"^  m_Name:\s*(.+)$", text, source).strip()
    vertex_count = int(_capture(r"^    m_VertexCount:\s*(\d+)$", text, source))
    data_size = int(_capture(r"^    m_DataSize:\s*(\d+)$", text, source))
    index_format = int(_capture(r"^  m_IndexFormat:\s*(\d+)$", text, source))
    vertex_data = bytes.fromhex(_capture(r"^    _typelessdata:\s*([0-9a-fA-F]+)$", text, source))
    index_data = bytes.fromhex(_capture(r"^  m_IndexBuffer:\s*([0-9a-fA-F]+)$", text, source))
    channels = _channels(text, source)
    submeshes = _submeshes(text, source)

    if len(vertex_data) != data_size or data_size % vertex_count:
        raise RuntimeError(
            f"Invalid vertex buffer for {source}: bytes={len(vertex_data)}, "
            f"declared={data_size}, vertices={vertex_count}"
        )
    stride = data_size // vertex_count
    if any(channel.stream != 0 for channel in channels if channel.dimension):
        raise RuntimeError(f"Multi-stream Mesh assets are not supported: {source}")
    if len(channels) <= 4 or channels[0].dimension != 3:
        raise RuntimeError(f"Position/UV channel contract is missing: {source}")

    position = channels[0]
    normal = channels[1] if len(channels) > 1 and channels[1].dimension == 3 else None
    uv0 = channels[4] if len(channels) > 4 and channels[4].dimension >= 2 else None
    index_stride = 2 if index_format == 0 else 4
    index_code = "H" if index_stride == 2 else "I"

    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("w", encoding="utf-8", newline="\n", buffering=1024 * 1024) as stream:
        stream.write(f"# Extracted losslessly from Unity Mesh asset: {source.as_posix()}\n")
        stream.write(f"o {name}\n")
        for vertex in range(vertex_count):
            base = vertex * stride
            x, y, z = _floats(vertex_data, base + position.offset, 3, position.format)
            stream.write(f"v {z * 100.0:.9g} {x * 100.0:.9g} {y * 100.0:.9g}\n")
        if uv0:
            for vertex in range(vertex_count):
                base = vertex * stride
                u, v = _floats(vertex_data, base + uv0.offset, 2, uv0.format)
                stream.write(f"vt {u:.9g} {v:.9g}\n")
        else:
            # Unreal's Interchange OBJ translator expects a UV index whenever
            # normals are indexed, even though OBJ formally permits v//vn.
            # A deterministic zero UV keeps untextured procedural meshes valid
            # and avoids an engine ensure during unattended imports.
            for _ in range(vertex_count):
                stream.write("vt 0 0\n")
        if normal:
            for vertex in range(vertex_count):
                base = vertex * stride
                x, y, z = _floats(vertex_data, base + normal.offset, 3, normal.format)
                stream.write(f"vn {z:.9g} {x:.9g} {y:.9g}\n")

        def face_vertex(index: int) -> str:
            obj = index + 1
            if normal:
                return f"{obj}/{obj}/{obj}"
            return f"{obj}/{obj}"

        for submesh_index, submesh in enumerate(submeshes):
            if submesh["topology"] != 0 or submesh["indexCount"] % 3:
                raise RuntimeError(f"Only triangle submeshes are supported: {source}")
            stream.write(f"g {name}_Submesh{submesh_index}\n")
            byte_offset = submesh["firstByte"]
            count = submesh["indexCount"]
            required = byte_offset + count * index_stride
            if required > len(index_data):
                raise RuntimeError(f"Index range exceeds buffer in {source}")
            indices = struct.unpack_from("<" + index_code * count, index_data, byte_offset)
            base_vertex = submesh["baseVertex"]
            for offset in range(0, count, 3):
                a, b, c = (indices[offset + corner] + base_vertex for corner in range(3))
                if max(a, b, c) >= vertex_count:
                    raise RuntimeError(f"Out-of-range index in {source}")
                stream.write(
                    f"f {face_vertex(a)} {face_vertex(b)} {face_vertex(c)}\n"
                )

    return {
        "source": source.as_posix(),
        "guid": _guid(source),
        "name": name,
        "obj": destination.as_posix(),
        "vertices": vertex_count,
        "indices": sum(item["indexCount"] for item in submeshes),
        "submeshes": len(submeshes),
        "sha256": hashlib.sha256(destination.read_bytes()).hexdigest(),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    workspace = Path(__file__).resolve().parents[2]
    parser.add_argument("--unity-root", type=Path, default=workspace / "Game")
    parser.add_argument(
        "--output-root",
        type=Path,
        default=workspace / "Unreal" / "Migration" / "UnityEmbeddedMeshes",
    )
    args = parser.parse_args()

    results = []
    for relative in SOURCE_ASSETS:
        source = args.unity_root / Path(relative)
        if not source.is_file():
            raise FileNotFoundError(source)
        guid = _guid(source)
        destination = args.output_root / guid / f"{source.stem}.obj"
        result = _extract(source, destination)
        result["source"] = relative
        result["obj"] = destination.relative_to(workspace / "Unreal").as_posix()
        results.append(result)
        print(
            f"[CML Embedded Mesh] {relative}: vertices={result['vertices']}, "
            f"indices={result['indices']}"
        )

    report = workspace / "Unreal" / "Migration" / "unity_embedded_mesh_extract_report.json"
    temporary = report.with_suffix(".json.tmp")
    temporary.write_text(
        json.dumps({"schema": 1, "converted": len(results), "failed": 0, "results": results}, indent=2)
        + "\n",
        encoding="utf-8",
    )
    temporary.replace(report)
    print(f"[CML Embedded Mesh] Complete: converted={len(results)}, failed=0")


if __name__ == "__main__":
    main()
